### ISSUE TITLE
Bugs in convex relaxation

### ISSUE THREAD

**Issue by jtmatterer** [jhu-graphstat/LSGMcode#11]
[relaxed_normAPPB_FW_seeds.m ](https://github.com/jhu-graphstat/LSGMcode/blob/master/algorithms/relaxed_normAPPB_FW_seeds.m)
- The initial matrix `P`  is not doubly stochastic
- The way this function is called in [seededgraphmatchell2.m](https://github.com/jhu-graphstat/LSGMcode/blob/master/algorithms/seedgraphmatchell2.m#L61) (i.e., on the matrices `A22, B22`)  it should not involve seeds
- The objective function and gradient calculations do not take the seed structure into account

**Comment by dpmcsuss** [comment]
@thegreatginski any thoughts on this? Are these easily fixable? Could help greatly with speed if we get the seeds in there, no?

**Comment by dpmcsuss** [comment]
@thegreatginski said (via email as opposed to here ;-)

> the way i use it is thus:
> 
> ``` matlab
> P= relaxed_normAPPB_FW_seeds(A,B,m);
> 
> P=P(m+1:n,m+1:n);
> 
> if (m==0)
>     P=P;
> else
>     PP=[[eye(m),zeros(m,n-m)];[zeros(n-m,m),P]];
> end
> ```
> 
> I think that fixes everything

**Comment by dpmcsuss** [comment]
@thegreatginski Are you referring to how it is used in [seededgraphmatchell2.m](https://github.com/jhu-graphstat/LSGMcode/blob/master/algorithms/seedgraphmatchell2.m#L61)?

**Comment by thegreatginski** [comment]
i think that is how it is used.  i remember marcelo (who wrote the convex
code) saying something akin to this.  does the code not seed during the
gradient calculations?  if that's the case, i have the R version with all
the gradient and everything written out (i wrote the code, so am 65% sure
it is good ;-)
it should be fast to translate to matlab.
cheers
vince

**Comment by dpmcsuss** [comment]
I think its just wrong on that line 61 above. Because it is called with only the nonSeed-to-nonSeed adjacency matrices and then also a seed. So yeah, its strange.
