### ISSUE TITLE
Recursive Spectral Clustering

### ISSUE THREAD

**Issue by dpmcsuss** [jhu-graphstat/LSGMcode#14]
This will recurse through the spectral clustering step until cluster sizes are reasonable.

**Comment by jtmatterer** [comment]
See

algorithms/kmeansHybrid.m 

For an implementation of kmeans with a recursive divisive step. It still has the problem of taking too long to cluster large data sets of very similar data, i.e., the kind we get from real twitter and instagram graphs.

**Comment by jtmatterer** [comment]
This is finally implemented to a sufficient degree of both accuracy and speed in [jointCluster.m](https://github.com/jhu-graphstat/LSGMcode/blob/unequalGraphs/algorithms/jointCluster.m) in the unequalGraphs branch.
