### ISSUE TITLE
Implement Jasons soft/many-to-many matching scheme

### ISSUE THREAD

**Issue by dpmcsuss** [jhu-graphstat/LSGMcode#4]

**Comment by jtmatterer** [comment]
One-to-many matching is now available as an option in BigGMr.

**Comment by dpmcsuss** [comment]
See 641dc1048d400d53856a177971a15a7c01e16416, 58869096f1c27699cb044282bceaf72bee4ec2c6 and 86be2f37a803e62feaa2bdf98e1dbe709eb18b5a
